[phases.setup]
nixPkgs = ["python311", "cairo", "pango", "gdk-pixbuf", "libffi"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"]

[start]
cmd = "python start_server.py"
